const data = {
  EvolutionSets: [
    {
      id: 1,
      name: "Moon",
      BeastTemplates: [
        {
          dexNumber: 1,
          name: "Moon",
          type: "Electric",
          description:
            "A Moon slightly resembles a bunny. With strange ears on it’s head it shocks everything around it.",
          starLevel: 1,
          basicSkills: ["Triple Kick", "Gravity Pull", "Moon Shock"],
          ultimateSkill: "Mega Volt Crash",
          image: {
            url: "https://bafkreic6t7y5pfph5v6pqx556dr3qv7wsip62nyxjbpc2povll5t5mxv4i.ipfs.dweb.link/",
          },
          color: "#ffd966",
        },
        {
          dexNumber: 2,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
        },
        {
          dexNumber: 3,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
        },
      ],
    },
    {
      id: 2,
      name: "Saber",
      BeastTemplates: [
        {
          dexNumber: 4,
          name: "Saber",
          type: "Electric",
          description:
            "A Moon slightly resembles a bunny. With strange ears on it’s head it shocks everything around it.",
          starLevel: 1,
          basicSkills: ["Triple Kick", "Gravity Pull", "Moon Shock"],
          ultimateSkill: "Mega Volt Crash",
          image: {
            url: "https://bafkreibqzbk77wqsvl7v7cqjef2l3tnmnge6afhriwaslwzv7qrhtynjbi.ipfs.dweb.link/",
          },
          color: "#A4C2F4",
        },
        {
          dexNumber: 5,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
        },
        {
          dexNumber: 6,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
        },
      ],
    },
    {
      id: 3,
      name: "Shen",
      BeastTemplates: [
        {
          dexNumber: 7,
          name: "Shen",
          type: "Electric",
          description:
            "A Moon slightly resembles a bunny. With strange ears on it’s head it shocks everything around it.",
          starLevel: 1,
          basicSkills: ["Triple Kick", "Gravity Pull", "Moon Shock"],
          ultimateSkill: "Mega Volt Crash",
          image: {
            url: "https://bafkreiffxvsww3vrrjisatw2ykouhif3wbmw6gv57dclzcd6gmvtadhk5q.ipfs.dweb.link/",
          },
          color: "#B7D7A8",
        },
        {
          dexNumber: 8,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
        },
        {
          dexNumber: 9,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
        },
      ],
    },
    {
      id: 4,
      name: "Azazel",
      BeastTemplates: [
        {
          dexNumber: 10,
          name: "Azazel",
          type: "Electric",
          description:
            "A Moon slightly resembles a bunny. With strange ears on it’s head it shocks everything around it.",
          starLevel: 1,
          basicSkills: ["Triple Kick", "Gravity Pull", "Moon Shock"],
          ultimateSkill: "Mega Volt Crash",
          image: {
            url: "https://bafkreihdeh2ritfc55kuvjmkgd3nbxqbiwyap7dvtjjn762bchzydzotuy.ipfs.dweb.link/",
          },
          color: "#EA9999",
        },
        {
          dexNumber: 11,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
        },
        {
          dexNumber: 12,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
        },
      ],
    },
    {
      id: 5,
      name: "Teddy",
      BeastTemplates: [
        {
          dexNumber: 13,
          name: "Teddy",
          type: "Electric",
          description:
            "A Moon slightly resembles a bunny. With strange ears on it’s head it shocks everything around it.",
          starLevel: 1,
          basicSkills: ["Triple Kick", "Gravity Pull", "Moon Shock"],
          ultimateSkill: "Mega Volt Crash",
          image: {
            url: "https://bafkreihuijcqetjfppzpbabxs25wafzk6dscdmbw2gwnqyxkycpauowzce.ipfs.dweb.link/",
          },
          color: "#D5A6BD",
        },
        {
          dexNumber: 14,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
        },
        {
          dexNumber: 15,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
        },
      ],
    },
  ],
}

export default data
