const data = {
  EvolutionSets: [
    {
      id: 1,
      name: "Moon",
      BeastTemplates: [
        {
          dexNumber: 1,
          name: "Moon",
          type: "Electric",
          description:
            "A Moon slightly resembles a bunny. With strange ears on it’s head it shocks everything around it.",
          starLevel: 1,
          basicSkills: ["Triple Kick", "Gravity Pull", "Moon Shock"],
          ultimateSkill: "Mega Volt Crash",
          image: {
            url: "https://bafkreic6t7y5pfph5v6pqx556dr3qv7wsip62nyxjbpc2povll5t5mxv4i.ipfs.dweb.link/",
          },
          color: "#ffd966",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 2,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
          buttonBackground: "#CAB77E",
          buttonOutset: "#8F7A39",
          buttonInset: "#BBA259",
        },
        {
          dexNumber: 3,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
          buttonBackground: "#CAB77E",
          buttonOutset: "#8F7A39",
          buttonInset: "#BBA259",
        },
      ],
    },
    {
      id: 2,
      name: "Saber",
      BeastTemplates: [
        {
          dexNumber: 4,
          name: "Saber",
          type: "Water",
          description:
            "A Saber loves to smile. It has teeth so strong that can break even diamond hands…",
          starLevel: 1,
          basicSkills: ["Frenzy", "Water Drop", "Saber Bite"],
          ultimateSkill: "Supersonic Wave",
          image: {
            url: "https://bafkreibqzbk77wqsvl7v7cqjef2l3tnmnge6afhriwaslwzv7qrhtynjbi.ipfs.dweb.link/",
          },
          color: "#A4C2F4",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 5,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 6,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
      ],
    },
    {
      id: 3,
      name: "Shen",
      BeastTemplates: [
        {
          dexNumber: 7,
          name: "Shen",
          type: "Grass",
          description: "A Shen is said to be born from magical dust.",
          starLevel: 1,
          basicSkills: ["Camouflage", "Magic Dust", "Petal Wish"],
          ultimateSkill: "Tackle",
          image: {
            url: "https://bafkreiffxvsww3vrrjisatw2ykouhif3wbmw6gv57dclzcd6gmvtadhk5q.ipfs.dweb.link/",
          },
          color: "#B7D7A8",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 8,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 9,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
      ],
    },
    {
      id: 4,
      name: "Azazel",
      BeastTemplates: [
        {
          dexNumber: 10,
          name: "Azazel",
          type: "Fire",
          description:
            "An Azazel is afraid of darkness. It closes its eyes when it senses danger.",
          starLevel: 1,
          basicSkills: ["Overheat", "Blazing Strike", "Fire Ball"],
          ultimateSkill: "Phantom Force",
          image: {
            url: "https://bafkreihdeh2ritfc55kuvjmkgd3nbxqbiwyap7dvtjjn762bchzydzotuy.ipfs.dweb.link/",
          },
          color: "#EA9999",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 11,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 12,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
      ],
    },
    {
      id: 5,
      name: "Teddy",
      BeastTemplates: [
        {
          dexNumber: 13,
          name: "Teddy",
          type: "Normal",
          description: "A Teddy never sleeps. It eats when it’s stressed.",
          starLevel: 1,
          basicSkills: ["Silent Fart", "Frustration", "Depression"],
          ultimateSkill: "Hyper Room",
          image: {
            url: "https://bafkreihuijcqetjfppzpbabxs25wafzk6dscdmbw2gwnqyxkycpauowzce.ipfs.dweb.link/",
          },
          color: "#D5A6BD",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 14,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
        {
          dexNumber: 15,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
        },
      ],
    },
  ],
}

export default data
