const data = {
  EvolutionSets: [
    {
      id: 1,
      name: "Moon",
      BeastTemplates: [
        {
          dexNumber: 1,
          name: "Moon",
          type: "Electric",
          description:
            "A Moon slightly resembles a bunny. With strange ears on it’s head it shocks everything around it.",
          starLevel: 1,
          basicSkills: ["Triple Kick", "Gravity Pull", "Moon Shock"],
          ultimateSkill: "Mega Volt Crash",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/001_normal.png",
          },
          color: "#ffd966",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
          typeTagBackground: "#E6CE86",
          typeTagOutset: "#B3A068",
          typeTagInset: "#CCB777",
        },
        {
          dexNumber: 2,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
          buttonBackground: "#CAB77E",
          buttonOutset: "#8F7A39",
          buttonInset: "#BBA259",
          typeTagBackground: "#CAB77E",
          typeTagOutset: "#8F7A39",
          typeTagInset: "#BBA259",
        },
        {
          dexNumber: 3,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
          buttonBackground: "#CAB77E",
          buttonOutset: "#8F7A39",
          buttonInset: "#BBA259",
          typeTagBackground: "#CAB77E",
          typeTagOutset: "#8F7A39",
          typeTagInset: "#BBA259",
        },
      ],
    },
    {
      id: 2,
      name: "Saber",
      BeastTemplates: [
        {
          dexNumber: 4,
          name: "Saber",
          type: "Water",
          description:
            "A Saber loves to smile. It has teeth so strong that can break even diamond hands…",
          starLevel: 1,
          basicSkills: ["Frenzy", "Water Drop", "Saber Bite"],
          ultimateSkill: "Supersonic Wave",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/004_normal.png",
          },
          color: "#A4C2F4",
          buttonBackground: "#A4C2F4",
          buttonOutset: "#7388AB",
          buttonInset: "#94AFDC",
          typeTagBackground: "#ACBFDE",
          typeTagOutset: "#8694AD",
          typeTagInset: "#99AAC6",
        },
        {
          dexNumber: 5,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
          buttonBackground: "#7388AB",
          buttonOutset: "#515F78",
          buttonInset: "#687A9A",
          typeTagBackground: "#839BC3",
          typeTagOutset: "#515F78",
          typeTagInset: "#8194B3",
        },
        {
          dexNumber: 6,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
          buttonBackground: "#7388AB",
          buttonOutset: "#515F78",
          buttonInset: "#687A9A",
          typeTagBackground: "#839BC3",
          typeTagOutset: "#515F78",
          typeTagInset: "#8194B3",
        },
      ],
    },
    {
      id: 3,
      name: "Shen",
      BeastTemplates: [
        {
          dexNumber: 7,
          name: "Shen",
          type: "Grass",
          description: "A Shen is said to be born from magical dust.",
          starLevel: 1,
          basicSkills: ["Camouflage", "Magic Dust", "Petal Wish"],
          ultimateSkill: "Tackle",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/007_normal.png",
          },
          color: "#B7D7A8",
          buttonBackground: "#B7D7A8",
          buttonOutset: "#92AC86",
          buttonInset: "#A5C297",
          typeTagBackground: "#A5C297",
          typeTagOutset: "#809776",
          typeTagInset: "#92AC86",
        },
        {
          dexNumber: 8,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
          buttonBackground: "#809776",
          buttonOutset: "#66795E",
          buttonInset: "#73886A",
          typeTagBackground: "#A6B69F",
          typeTagOutset: "#66795E",
          typeTagInset: "#8DA184",
        },
        {
          dexNumber: 9,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
          buttonBackground: "#809776",
          buttonOutset: "#66795E",
          buttonInset: "#73886A",
          typeTagBackground: "#A6B69F",
          typeTagOutset: "#66795E",
          typeTagInset: "#8DA184",
        },
      ],
    },
    {
      id: 4,
      name: "Azazel",
      BeastTemplates: [
        {
          dexNumber: 10,
          name: "Azazel",
          type: "Fire",
          description:
            "An Azazel is afraid of darkness. It closes its eyes when it senses danger.",
          starLevel: 1,
          basicSkills: ["Overheat", "Blazing Strike", "Fire Ball"],
          ultimateSkill: "Phantom Force",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/010_normal.png",
          },
          color: "#EA9999",
          buttonBackground: "#EA9999",
          buttonOutset: "#BB7A7A",
          buttonInset: "#D38A8A",
          typeTagBackground: "#D38A8A",
          typeTagOutset: "#A46B6B",
          typeTagInset: "#BB7A7A",
        },
        {
          dexNumber: 11,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
          buttonBackground: "#A46B6B",
          buttonOutset: "#835656",
          buttonInset: "#946060",
          typeTagBackground: "#B68989",
          typeTagOutset: "#734B4B",
          typeTagInset: "#AD7A7A",
        },
        {
          dexNumber: 12,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
          buttonBackground: "#A46B6B",
          buttonOutset: "#835656",
          buttonInset: "#946060",
          typeTagBackground: "#B68989",
          typeTagOutset: "#734B4B",
          typeTagInset: "#AD7A7A",
        },
      ],
    },
    {
      id: 5,
      name: "Teddy",
      BeastTemplates: [
        {
          dexNumber: 13,
          name: "Teddy",
          type: "Normal",
          description: "A Teddy never sleeps. It eats when it’s stressed.",
          starLevel: 1,
          basicSkills: ["Silent Fart", "Frustration", "Depression"],
          ultimateSkill: "Hyper Room",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/013_normal.png",
          },
          color: "#D5A6BD",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#957484",
          typeTagInset: "#AA8597",
        },
        {
          dexNumber: 14,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#6F5562",
          typeTagInset: "#AA8597",
        },
        {
          dexNumber: 15,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#6F5562",
          typeTagInset: "#AA8597",
        },
      ],
    },
    {
      id: 6,
      name: "Viper",
      BeastTemplates: [
        {
          dexNumber: 16,
          name: "Viper",
          type: "Electric",
          description: "A Viper moves at blinding speeds.",
          starLevel: 1,
          basicSkills: ["Paralyze Shot", "Twist", "Electric Shield"],
          ultimateSkill: "Lightning Wrap",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/016_normal.png",
          },
          color: "#ffd966",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
          typeTagBackground: "#E6CE86",
          typeTagOutset: "#B3A068",
          typeTagInset: "#CCB777",
        },
        {
          dexNumber: 17,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
          buttonBackground: "#CAB77E",
          buttonOutset: "#8F7A39",
          buttonInset: "#BBA259",
          typeTagBackground: "#CAB77E",
          typeTagOutset: "#8F7A39",
          typeTagInset: "#BBA259",
        },
        {
          dexNumber: 18,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
          buttonBackground: "#CAB77E",
          buttonOutset: "#8F7A39",
          buttonInset: "#BBA259",
          typeTagBackground: "#CAB77E",
          typeTagOutset: "#8F7A39",
          typeTagInset: "#BBA259",
        },
      ],
    },
    {
      id: 7,
      name: "Blob",
      BeastTemplates: [
        {
          dexNumber: 19,
          name: "Blob",
          type: "Water",
          description:
            "A Blob lives in secrecy underwater. It becomes invisible when wet.",
          starLevel: 1,
          basicSkills: ["Water Punch", "Mambo", "Stinging Blow"],
          ultimateSkill: "Bi Blast",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/019_normal.png",
          },
          color: "#A4C2F4",
          buttonBackground: "#A4C2F4",
          buttonOutset: "#7388AB",
          buttonInset: "#94AFDC",
          typeTagBackground: "#ACBFDE",
          typeTagOutset: "#8694AD",
          typeTagInset: "#99AAC6",
        },
        {
          dexNumber: 20,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
          buttonBackground: "#7388AB",
          buttonOutset: "#515F78",
          buttonInset: "#687A9A",
          typeTagBackground: "#839BC3",
          typeTagOutset: "#515F78",
          typeTagInset: "#8194B3",
        },
        {
          dexNumber: 21,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
          buttonBackground: "#7388AB",
          buttonOutset: "#515F78",
          buttonInset: "#687A9A",
          typeTagBackground: "#839BC3",
          typeTagOutset: "#515F78",
          typeTagInset: "#8194B3",
        },
      ],
    },
    {
      id: 8,
      name: "Coco",
      BeastTemplates: [
        {
          dexNumber: 22,
          name: "Coco",
          type: "Grass",
          description:
            "A Coco loves to sneak into things that makes it be unnoticeable.",
          starLevel: 1,
          basicSkills: ["Drain", "Coco Dance", "Attack and Hide"],
          ultimateSkill: "Savage Strikes",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/022_normal.png",
          },
          color: "#B7D7A8",
          buttonBackground: "#B7D7A8",
          buttonOutset: "#92AC86",
          buttonInset: "#A5C297",
          typeTagBackground: "#A5C297",
          typeTagOutset: "#809776",
          typeTagInset: "#92AC86",
        },
        {
          dexNumber: 23,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
          buttonBackground: "#809776",
          buttonOutset: "#66795E",
          buttonInset: "#73886A",
          typeTagBackground: "#A6B69F",
          typeTagOutset: "#66795E",
          typeTagInset: "#8DA184",
        },
        {
          dexNumber: 24,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
          buttonBackground: "#809776",
          buttonOutset: "#66795E",
          buttonInset: "#73886A",
          typeTagBackground: "#A6B69F",
          typeTagOutset: "#66795E",
          typeTagInset: "#8DA184",
        },
      ],
    },
    {
      id: 9,
      name: "Drago",
      BeastTemplates: [
        {
          dexNumber: 25,
          name: "Drago",
          type: "Fire",
          description: "A Drago has small wings but it cannot fly.",
          starLevel: 1,
          basicSkills: ["Fire Fury", "Burning Blow", "Ignite"],
          ultimateSkill: "Lava Bash",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/025_normal.png",
          },
          color: "#EA9999",
          buttonBackground: "#EA9999",
          buttonOutset: "#BB7A7A",
          buttonInset: "#D38A8A",
          typeTagBackground: "#D38A8A",
          typeTagOutset: "#A46B6B",
          typeTagInset: "#BB7A7A",
        },
        {
          dexNumber: 26,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
          buttonBackground: "#A46B6B",
          buttonOutset: "#835656",
          buttonInset: "#946060",
          typeTagBackground: "#B68989",
          typeTagOutset: "#734B4B",
          typeTagInset: "#AD7A7A",
        },
        {
          dexNumber: 27,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
          buttonBackground: "#A46B6B",
          buttonOutset: "#835656",
          buttonInset: "#946060",
          typeTagBackground: "#B68989",
          typeTagOutset: "#734B4B",
          typeTagInset: "#AD7A7A",
        },
      ],
    },
    {
      id: 10,
      name: "Chan",
      BeastTemplates: [
        {
          dexNumber: 28,
          name: "Chan",
          type: "Normal",
          description:
            "A Chan is said to steal one's spirit when looking into its eyes. It is very emotional.",
          starLevel: 1,
          basicSkills: ["Vanish", "Creep Show", "Summoning Clone"],
          ultimateSkill: "Explode",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/028_normal.png",
          },
          color: "#D5A6BD",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#957484",
          typeTagInset: "#AA8597",
        },
        {
          dexNumber: 29,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#6F5562",
          typeTagInset: "#AA8597",
        },
        {
          dexNumber: 30,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#6F5562",
          typeTagInset: "#AA8597",
        },
      ],
    },
    ,
    {
      id: 11,
      name: "Cron",
      BeastTemplates: [
        {
          dexNumber: 31,
          name: "Cron",
          type: "Electric",
          description:
            "A Cron moves in groups. Together they create a strong magnetic field.",
          starLevel: 1,
          basicSkills: ["Volt Slam", "Recharge", "Magnetic Clutch"],
          ultimateSkill: "Thunder Spin",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/031_normal.png",
          },
          color: "#ffd966",
          buttonBackground: "#FFE595",
          buttonOutset: "#B3A068",
          buttonInset: "#E6CE86",
          typeTagBackground: "#E6CE86",
          typeTagOutset: "#B3A068",
          typeTagInset: "#CCB777",
        },
        {
          dexNumber: 32,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
          buttonBackground: "#CAB77E",
          buttonOutset: "#8F7A39",
          buttonInset: "#BBA259",
          typeTagBackground: "#CAB77E",
          typeTagOutset: "#8F7A39",
          typeTagInset: "#BBA259",
        },
        {
          dexNumber: 33,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#B39847",
          buttonBackground: "#CAB77E",
          buttonOutset: "#8F7A39",
          buttonInset: "#BBA259",
          typeTagBackground: "#CAB77E",
          typeTagOutset: "#8F7A39",
          typeTagInset: "#BBA259",
        },
      ],
    },
    {
      id: 12,
      name: "Octo",
      BeastTemplates: [
        {
          dexNumber: 34,
          name: "Octo",
          type: "Water",
          description:
            "An Octo is a martial arts specialist. Give it the right tools and it will make delicious food.",
          starLevel: 1,
          basicSkills: ["Aqua Jab", "Magic Whip", "Hydro Chop"],
          ultimateSkill: "Ink Bomb",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/034_normal.png",
          },
          color: "#A4C2F4",
          buttonBackground: "#A4C2F4",
          buttonOutset: "#7388AB",
          buttonInset: "#94AFDC",
          typeTagBackground: "#ACBFDE",
          typeTagOutset: "#8694AD",
          typeTagInset: "#99AAC6",
        },
        {
          dexNumber: 35,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
          buttonBackground: "#7388AB",
          buttonOutset: "#515F78",
          buttonInset: "#687A9A",
          typeTagBackground: "#839BC3",
          typeTagOutset: "#515F78",
          typeTagInset: "#8194B3",
        },
        {
          dexNumber: 36,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#7388AB",
          buttonBackground: "#7388AB",
          buttonOutset: "#515F78",
          buttonInset: "#687A9A",
          typeTagBackground: "#839BC3",
          typeTagOutset: "#515F78",
          typeTagInset: "#8194B3",
        },
      ],
    },
    {
      id: 13,
      name: "Coco",
      BeastTemplates: [
        {
          dexNumber: 37,
          name: "Ezme",
          type: "Grass",
          description: "An Ezme has a green bright shine during the night.",
          starLevel: 1,
          basicSkills: ["Snap Trap", "Solar Heal", "Leaf Blade"],
          ultimateSkill: "Powder",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/037_normal.png",
          },
          color: "#B7D7A8",
          buttonBackground: "#B7D7A8",
          buttonOutset: "#92AC86",
          buttonInset: "#A5C297",
          typeTagBackground: "#A5C297",
          typeTagOutset: "#809776",
          typeTagInset: "#92AC86",
        },
        {
          dexNumber: 38,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
          buttonBackground: "#809776",
          buttonOutset: "#66795E",
          buttonInset: "#73886A",
          typeTagBackground: "#A6B69F",
          typeTagOutset: "#66795E",
          typeTagInset: "#8DA184",
        },
        {
          dexNumber: 39,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#809776",
          buttonBackground: "#809776",
          buttonOutset: "#66795E",
          buttonInset: "#73886A",
          typeTagBackground: "#A6B69F",
          typeTagOutset: "#66795E",
          typeTagInset: "#8DA184",
        },
      ],
    },
    {
      id: 14,
      name: "Luci",
      BeastTemplates: [
        {
          dexNumber: 40,
          name: "Luci",
          type: "Fire",
          description:
            "A Luci is an infernal beast. When it's angered, its spearheaded tail will put anything on fire.",
          starLevel: 1,
          basicSkills: ["Burn Up", "Nightmare", "Fire Flare"],
          ultimateSkill: "End Game",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/040_normal.png",
          },
          color: "#EA9999",
          buttonBackground: "#EA9999",
          buttonOutset: "#BB7A7A",
          buttonInset: "#D38A8A",
          typeTagBackground: "#D38A8A",
          typeTagOutset: "#A46B6B",
          typeTagInset: "#BB7A7A",
        },
        {
          dexNumber: 41,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
          buttonBackground: "#A46B6B",
          buttonOutset: "#835656",
          buttonInset: "#946060",
          typeTagBackground: "#B68989",
          typeTagOutset: "#734B4B",
          typeTagInset: "#AD7A7A",
        },
        {
          dexNumber: 42,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#A46B6B",
          buttonBackground: "#A46B6B",
          buttonOutset: "#835656",
          buttonInset: "#946060",
          typeTagBackground: "#B68989",
          typeTagOutset: "#734B4B",
          typeTagInset: "#AD7A7A",
        },
      ],
    },
    {
      id: 15,
      name: "Stabbie",
      BeastTemplates: [
        {
          dexNumber: 43,
          name: "Stabbie",
          type: "Normal",
          description:
            "A Stabbie holds a toy knife to persuade others to do its bidding.",
          starLevel: 1,
          basicSkills: ["Stab It", "Intimidate", "Duck-Ya Up"],
          ultimateSkill: "One-Sword Style",
          image: {
            url: "https://raw.githubusercontent.com/basicbeasts/basic-beasts-frontend/main/public/beasts/043_normal.png",
          },
          color: "#D5A6BD",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#957484",
          typeTagInset: "#AA8597",
        },
        {
          dexNumber: 44,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 2,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#6F5562",
          typeTagInset: "#AA8597",
        },
        {
          dexNumber: 45,
          name: "???",
          type: "???",
          description: "??",
          starLevel: 3,
          basicSkills: ["??", "??", "??"],
          ultimateSkill: "??",
          color: "#957484",
          buttonBackground: "#D5A6BD",
          buttonOutset: "#AA8597",
          buttonInset: "#C095AA",
          typeTagBackground: "#C095AA",
          typeTagOutset: "#6F5562",
          typeTagInset: "#AA8597",
        },
      ],
    },
  ],
}

export default data
